---
- name: debian | Installing Guacamole Pre-Reqs
  apt:
    name: "{{ guacamole_debian_pre_reqs }}"
    state: present
  become: true
  register: result
  until: result is successful

# - name: debian | Configuring Tomcat Default Config
#   template:
#     src: "{{ 'etc/default/' + guacamole_tomcat + '.j2' }}"
#     dest: "{{ '/etc/default/' + guacamole_tomcat }}"
#     owner: root
#     group: root
#     mode: u=rw,g=r,o=r
#   become: true
#   notify:
#     - "restart {{ guacamole_tomcat }}"
#     - restart guacd
