---
- name: set_facts | Setting Debian set_facts
  block:

    - name: set_facts | Setting Debian < 9 set_facts
      ansible.builtin.set_fact:
        guacamole_freerdp: freerdp-x11
        guacamole_freerdp_dev: libfreerdp-dev
        guacamole_tomcat: tomcat7
        guacamole_tomcat_service: tomcat7
        guacamole_tomcat_user: tomcat7
        guacamole_debian_pre_reqs:
          - tomcat7
          - build-essential
          - freerdp-x11
          - libavcodec-dev
          - libavutil-dev
          - libcairo2-dev
          - libfreerdp-dev
          - libjpeg62-turbo-dev
          - libossp-uuid-dev
          - libpango1.0-dev
          - libpng12-dev
          - libpulse-dev
          - libssh2-1-dev
          - libssl-dev
          - libswscale-dev
          - libtelnet-dev
          - libvncserver-dev
          - libvorbis-dev
          - libwebp-dev
      when: ansible_distribution_version is version('9', '<'))

    - name: set_facts | Setting Debian 9 set_facts
      ansible.builtin.set_fact:
        guacamole_freerdp: freerdp-x11
        guacamole_freerdp_dev: freerdp2-dev
        guacamole_tomcat: tomcat8
        guacamole_tomcat_service: tomcat8
        guacamole_tomcat_user: tomcat8
        guacamole_debian_pre_reqs:
          - tomcat8
          - build-essential
          - freerdp-x11
          - libavcodec-dev
          - libavutil-dev
          - libcairo2-dev
          - freerdp2-dev
          - libjpeg62-turbo-dev
          - libossp-uuid-dev
          - libpango1.0-dev
          - libpng-dev
          - libpulse-dev
          - libssh2-1-dev
          - libssl-dev
          - libswscale-dev
          - libtelnet-dev
          - libvncserver-dev
          - libvorbis-dev
          - libwebp-dev
      when: ansible_distribution_version is version('9', '==))

    - name: set_facts | Setting Debian > 9 Facts
      ansible.builtin.set_fact:
        guacamole_freerdp: freerdp2-x11
        guacamole_freerdp_dev: freerdp2-dev
        guacamole_tomcat: tomcat9
        guacamole_tomcat_service: tomcat9
        guacamole_tomcat_user: tomcat
        guacamole_debian_pre_reqs:
          - tomcat9
          - build-essential
          - freerdp2-x11
          - libavcodec-dev
          - libavutil-dev
          - libcairo2-dev
          - freerdp2-dev
          - libjpeg62-turbo-dev
          - libossp-uuid-dev
          - libpango1.0-dev
          - libpng-dev
          - libpulse-dev
          - libssh2-1-dev
          - libssl-dev
          - libswscale-dev
          - libtelnet-dev
          - libvncserver-dev
          - libvorbis-dev
          - libwebp-dev
      when: ansible_distribution_version is version('9', '>')

  when: ansible_distribution == "Debian"

- name: set_facts | Setting Ubuntu set_facts
  block:

    - name: set_facts | Setting Ubuntu < 18.04 set_facts
      ansible.builtin.set_fact:
        guacamole_freerdp: freerdp-x11
        guacamole_freerdp_dev: libfreerdp-dev
        guacamole_tomcat: tomcat7
        guacamole_tomcat_service: tomcat7
        guacamole_tomcat_user: tomcat7
        guacamole_debian_pre_reqs:
          - tomcat7
          - build-essential
          - dpkg-dev
          - freerdp-x11
          - ghostscript
          - libavcodec-dev
          - libavutil-dev
          - libcairo2-dev
          - libfreerdp-dev
          - libjpeg-turbo8-dev
          - libossp-uuid-dev
          - libpango1.0-dev
          - libpng12-dev
          - libpulse-dev
          - libssh2-1-dev
          - libssl-dev
          - libswscale-dev
          - libtelnet-dev
          - libvncserver-dev
          - libvorbis-dev
          - libwebp-dev
          - python3-pip
      when: ansible_distribution_version is version('18.04', '<')

    - name: set_facts | Setting Ubuntu 18.04-19.10 Facts
      ansible.builtin.set_fact:
        guacamole_freerdp: freerdp-x11
        guacamole_freerdp_dev: freerdp2-dev
        guacamole_tomcat: tomcat8
        guacamole_tomcat_service: tomcat8
        guacamole_tomcat_user: tomcat8
        guacamole_debian_pre_reqs:
          - tomcat8
          - build-essential
          - freerdp-x11
          - libavcodec-dev
          - libavutil-dev
          - libcairo2-dev
          - freerdp2-dev
          - libjpeg-turbo8-dev
          - libossp-uuid-dev
          - libpango1.0-dev
          - libpng-dev
          - libpulse-dev
          - libssh2-1-dev
          - libssl-dev
          - libswscale-dev
          - libtelnet-dev
          - libvncserver-dev
          - libvorbis-dev
          - libwebp-dev
          - python3-pip
      when: (ansible_distribution_version is version('18.04', '>=') and
        ansible_distribution_version is version('19.10', '<='))

    - name: set_facts | Setting Ubuntu >= 19.1 Facts
      ansible.builtin.set_fact:
        guacamole_freerdp: freerdp2-x11
        guacamole_freerdp_dev: freerdp2-dev
        guacamole_tomcat: tomcat9
        guacamole_tomcat_service: tomcat9
        guacamole_tomcat_user: tomcat
        guacamole_debian_pre_reqs:
          - tomcat9
          - build-essential
          - freerdp2-x11
          - libavcodec-dev
          - libavutil-dev
          - libcairo2-dev
          - freerdp2-dev
          - libjpeg-turbo8-dev
          - libossp-uuid-dev
          - libpango1.0-dev
          - libpng-dev
          - libpulse-dev
          - libssh2-1-dev
          - libssl-dev
          - libswscale-dev
          - libtelnet-dev
          - libvncserver-dev
          - libvorbis-dev
          - libwebp-dev
          - python3-pip
      when: ansible_distribution_version is version('19.10', '>=')

    - name: set_facts | Setting Ubuntu MySQL set_facts
      ansible.builtin.set_fact:
        guacamole_debian_pip_reqs:
          - PyMySQL
          - cryptography
        guacamole_debian_pre_reqs: "{{ guacamole_debian_pre_reqs + ['mysql-client'] }}"
      when: guacamole_mysql_auth

    - name: set_facts | Setting Ubuntu PostGres set_facts
      ansible.builtin.set_fact:
        guacamole_debian_pip_reqs:
          - psycopg2-binary
      when: guacamole_postgresql_auth

  when: ansible_distribution == "Ubuntu"


- name: set_facts | Setting RedHat Facts
  block: 
    - name: set_facts | Setting RedHat Facts
      ansible.builtin.set_fact:
        guacamole_tomcat: tomcat
        guacamole_tomcat_service: tomcat
        guacamole_tomcat_user: tomcat
        guacamole_redhat_pre_reqs:
          - tomcat
          - cairo-devel
          - ffmpeg-devel
          - freerdp-devel
          - gcc
          - libjpeg-turbo-devel
          - libpng-devel
          - libssh2-devel
          - libtelnet-devel
          - libvncserver-devel
          - libvorbis-devel
          - libwebp-devel
          - make
          # - maven
          - openssl-devel
          - pango-devel
          - pulseaudio-libs-devel
          - uuid-devel

  when: ansible_os_family == "RedHat"
