---
# handlers file for ansible-guacamole
- name: restart tomcat
  service:
    name: tomcat
    state: restarted
  become: true

- name: restart tomcat7
  service:
    name: tomcat7
    state: restarted
  become: true
